train_path = "D:/ml proj/Video-Captioning-main/data/training_data"
test_path = "D:/ml proj/Video-Captioning-main/data/testing_data"
batch_size = 320
learning_rate = 0.0007
epochs = 150
latent_dim = 512
num_encoder_tokens = 4096
num_decoder_tokens = 1500
time_steps_encoder = 80
max_probability = -1
save_model_path = 'D:/ml proj/Video-Captioning-main/model_final1'
validation_split = 0.15
max_length = 10
search_type = 'greedy'